server:
  port: 8081
  context-path: /demo
# name: demo
# age: 18
# context: "name: ${name}, age: ${age}"
spring:
  profiles:
    active: nodev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # 驱动名称
    url: jdbc:mysql://localhost:3306/spring?characterEncoding=UTF-8 # 地址
    username: root # 用户名
    password: 123456 # 密码
  jpa:
    database: MySQL
    hibernate:
       ddl-auto: update # 第一次会创建新表，之后再次启动有数据不会删除
       dialect: org.hibernate.dialect.MySQL5Dialect
   # show-sql: true # 显示sql语句
  thymeleaf:
    prefix: /templates/
    suffix: .html
  #mvc:
    #view: # 配置mvc视图层
      #prefix: /templates/
      #suffix: .html
   # static-path-pattern: /static/** # 访问静态资源 在resources目录下的static文件夹下